version: 0.0
os: windows
files:
   - source: .\css
     destination: C:\temp\Agile18F\css
   - source: .\fonts
     destination: C:\temp\Agile18F\fonts
   - source: .\images
     destination: C:\temp\Agile18F\images
   - source: .\js
     destination: C:\temp\Agile18F\js
   - source: .\maps
     destination: C:\temp\Agile18F\maps
   - source: .\swf
     destination: C:\temp\Agile18F\swf
   - source: .\inc\db_connect.php
     destination: C:\temp\Agile18F\inc\db_connect.php
   - source: .\inc\feeds.php
     destination: C:\temp\Agile18F\inc\feeds.php
   - source: .\inc\footer.php
     destination: C:\temp\Agile18F\inc\footer.php
   - source: .\inc\functions.php
     destination: C:\temp\Agile18F\inc\functions.php
   - source: .\inc\header.php
     destination: C:\temp\Agile18F\inc\header.php
   - source: .\inc\index.html
     destination: C:\temp\Agile18F\inc\index.html
   - source: .\inc\logout.php
     destination: C:\temp\Agile18F\inc\logout.php
   - source: .\inc\process_login.php
     destination: C:\temp\Agile18F\inc\process_login.php
   - source: .\about.php
     destination: C:\temp\Agile18F\about.php
   - source: .\app.js
     destination: C:\temp\Agile18F\app.js
   - source: .\index.html
     destination: C:\temp\Agile18F\index.html
   - source: .\index.php
     destination: C:\temp\Agile18F\index.php
   - source: .\login.php
     destination: C:\temp\Agile18F\login.php
   - source: .\minerva_license.md
     destination: C:\temp\Agile18F\minerva_license.md
   - source: .\README.md
     destination: C:\temp\Agile18F\README.md
   - source: .\appspec.yml
     destination: C:\temp\Agile18F\appspec.yml
   - source: .\openfda.sql
     destination: C:\temp\Agile18F\openfda.sql

